language: php

php:
  - 7.1

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction
  - npm i
  - yarn run prod

script:
  - php artisan key:generate
  - vendor/bin/phpunit
